### ISSUE TITLE
Publication Planner: Drag and drop disabled after error

### ISSUE THREAD

**Issue by matsrorbecker** [Infomaker/Dashboard-Plugin#17]
When you try to drag a published article to a slot, you get an error ("Can't drop published article"). Nothing wrong with that. But afterwards, drag and drop seems to be disabled for all articles, regardless of status. You have to reload the page to get it work again.

**Comment by hamzahalhariri** [comment]
Hi @matsrorbecker
This is not the place were you can report issues for Dashboard-Plugins like `Publication Planner`.

This repo for Dashboard-Developer-Plugin, if you have any issues with `Publication Planner` or any other plugins please report them in [Jira](https://jira.infomaker.se) or contact the support team.

Thanks.
