### ISSUE TITLE
Allow developers to set title attribute on Icon component

### ISSUE THREAD

**Issue by khlbrg** [Infomaker/Dashboard-Plugin#6]
Allow developers to set the title attribute on Icon component, (or maybe on all GUI component?)

`<GUI.Icon title="My title i here" iconClass="clockwise"/>`

**Comment by khlbrg** [comment]
I guess this goes for all GUI component

**Comment by hamzahalhariri** [comment]
<GUI.Icon text="My title i here" iconClass="clockwise"/>

add text prop to your <GUI.Icon/>

see: https://github.com/Infomaker/Dashboard-Plugin/wiki/GUI-Library#icon

**Comment by imjohansunden** [comment]
Added support for tooltip. Functionality will be released in next deploy.

The property will be named tooltip because some GUI components use the title prop for text content.

So a working example will look like

```js
<GUI.Icon tooltip="My title i here" iconClass="clockwise"/>
```

_all GUI components should support tooltip in the future.._
