### ISSUE TITLE
GUI.Dropdown doesn't resize when position to screen edges

### ISSUE THREAD

**Issue by khlbrg** [Infomaker/Dashboard-Plugin#7]
When dropdown is positioned to the right of the screen it doesn't grow to the left

![skarmavbild 2017-01-11 kl 15 06 17](https://cloud.githubusercontent.com/assets/195388/21851541/c432299c-d80f-11e6-9188-0b5db943efc6.png)

**Comment by hamzahalhariri** [comment]
<GUI.DropMenu align='right' items={items} />

add align prop 'right' to your <GUI.DropMenu/>

**Comment by imjohansunden** [comment]
Will be fixed in next deploy. @hamzahalhariri  is correct but this will be added automatically by the dropmenu component.

So now left, center and right is preferred alignments. If center wont fit it will automatically change to right instead.
